part of 'category_cubit.dart';

extension CategoryCubitMock on CategoryCubit {
  Future<void> mock() async {
    final additionalCategories = [
      'Fruits',
      'Vegetables',
      'Dairy',
      'Bakery',
      'Meat',
      'Seafood',
      'Frozen Foods',
      'Canned Goods',
      'Dry Goods',
      'Beverages',
      'Snacks',
      'Condiments',
      'Spices',
      'Grains',
      'Pasta',
      'Rice',
      'Cereal',
      'Oils',
      'Sauces',
      'Soups',
      'Broths',
      'Baking Supplies',
      'Sweets',
      'Chocolates',
      'Candy',
      'Nuts',
      'Seeds',
      'Dried Fruits',
      'Coffee',
      'Tea',
      'Juices',
      'Sodas',
      'Water',
      'Alcohol',
      'Beer',
      'Wine',
      'Spirits',
      'Baby Food',
      'Pet Food',
      'Household Supplies',
      'Paper Products',
      'Cleaning Supplies',
      'Personal Care',
      'Health Products',
      'Beauty Products',
      'Pharmacy',
      'First Aid',
      'Stationery',
      'Electronics',
      'Toys',
      'Games',
      'Books',
      'Magazines',
      'Flowers',
      'Plants',
      'Garden Supplies',
      'Outdoor Supplies',
      'Tools',
      'Hardware',
      'Automotive',
      'Clothing',
      'Footwear',
      'Accessories',
      'Jewelry',
      'Watches',
      'Bags',
      'Luggage',
      'Sports Equipment',
      'Fitness Equipment',
      'Camping Gear',
      'Fishing Gear',
      'Hunting Gear',
      'Cycling Gear',
      'Skiing Gear',
      'Snowboarding Gear',
      'Surfing Gear',
      'Swimming Gear',
      'Diving Gear',
      'Boating Gear',
      'Music Instruments',
      'Art Supplies',
      'Craft Supplies',
      'Party Supplies',
      'Gift Wrap',
      'Greeting Cards',
      'Seasonal Items',
      'Holiday Items',
      'Travel Accessories',
      'Pet Accessories',
      'Baby Accessories',
      'Office Supplies',
      'Furniture',
      'Home Decor',
      'Lighting',
      'Bedding',
      'Bath Supplies',
      'Kitchen Supplies',
      'Cookware',
      'Tableware',
      'Storage Solutions',
      'Organization Solutions',
    ];

    for (final categoryName in additionalCategories) {
      final category = ItemCategoryTableData(
        id: (additionalCategories.indexOf(categoryName) + 1).toString(),
        name: categoryName,
        description: 'Description for $categoryName',
        image: 'https://placehold.co/400',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );
      await database.into(database.itemCategoryTable).insertOnConflictUpdate(category);
    }
    await load();
  }

  Future<void> dropItemCategoryTable() async {
    await database.delete(database.itemCategoryTable).go();
    await load();
  }
}
