import 'package:sanu/ui/settings/models/item_currency.dart';

final currencies = <ItemCurrency>[
  const ItemCurrency(name: 'United States Dollar', code: 'USD'),
  const ItemCurrency(name: 'United Arab Emirates Dirham', code: 'AED'),
  const ItemCurrency(name: 'Afghan Afghani', code: 'AFN'),
  const ItemCurrency(name: 'Albanian Lek', code: 'ALL'),
  const ItemCurrency(name: 'Armenian Dram', code: 'AMD'),
  const ItemCurrency(name: 'Netherlands Antillean Guilder', code: 'ANG'),
  const ItemCurrency(name: 'Angolan Kwanza', code: 'AOA'),
  const ItemCurrency(name: 'Argentine Peso', code: 'ARS'),
  const ItemCurrency(name: 'Australian Dollar', code: 'AUD'),
  const ItemCurrency(name: 'Aruban Florin', code: 'AWG'),
  const ItemCurrency(name: 'Azerbaijani Manat', code: 'AZN'),
  const ItemCurrency(name: 'Bosnia-Herzegovina Convertible Mark', code: 'BAM'),
  const ItemCurrency(name: 'Barbadian Dollar', code: 'BBD'),
  const ItemCurrency(name: 'Bangladeshi Taka', code: 'BDT'),
  const ItemCurrency(name: 'Bulgarian Lev', code: 'BGN'),
  const ItemCurrency(name: 'Bahraini Dinar', code: 'BHD', digits: 3),
  const ItemCurrency(name: 'Burundian Franc', code: 'BIF', digits: 0),
  const ItemCurrency(name: 'Bermudian Dollar', code: 'BMD'),
  const ItemCurrency(name: 'Brunei Dollar', code: 'BND'),
  const ItemCurrency(name: 'Bolivian Boliviano', code: 'BOB'),
  const ItemCurrency(name: 'Brazilian Real', code: 'BRL'),
  const ItemCurrency(name: 'Bahamian Dollar', code: 'BSD'),
  const ItemCurrency(name: 'Bhutanese Ngultrum', code: 'BTN'),
  const ItemCurrency(name: 'Botswana Pula', code: 'BWP'),
  const ItemCurrency(name: 'Belarusian Ruble', code: 'BYN'),
  const ItemCurrency(name: 'Belize Dollar', code: 'BZD'),
  const ItemCurrency(name: 'Canadian Dollar', code: 'CAD'),
  const ItemCurrency(name: 'Congolese Franc', code: 'CDF'),
  const ItemCurrency(name: 'Swiss Franc', code: 'CHF'),
  const ItemCurrency(name: 'Chilean Peso', code: 'CLP', digits: 0),
  const ItemCurrency(name: 'Chinese Yuan', code: 'CNY'),
  const ItemCurrency(name: 'Colombian Peso', code: 'COP'),
  const ItemCurrency(name: 'Costa Rican Colón', code: 'CRC'),
  const ItemCurrency(name: 'Cuban Convertible Peso', code: 'CUC'),
  const ItemCurrency(name: 'Cuban Peso', code: 'CUP'),
  const ItemCurrency(name: 'Cape Verdean Escudo', code: 'CVE'),
  const ItemCurrency(name: 'Czech Koruna', code: 'CZK'),
  const ItemCurrency(name: 'Djiboutian Franc', code: 'DJF', digits: 0),
  const ItemCurrency(name: 'Danish Krone', code: 'DKK'),
  const ItemCurrency(name: 'Dominican Peso', code: 'DOP'),
  const ItemCurrency(name: 'Algerian Dinar', code: 'DZD'),
  const ItemCurrency(name: 'Egyptian Pound', code: 'EGP'),
  const ItemCurrency(name: 'Eritrean Nakfa', code: 'ERN'),
  const ItemCurrency(name: 'Ethiopian Birr', code: 'ETB'),
  const ItemCurrency(name: 'Euro', code: 'EUR'),
  const ItemCurrency(name: 'Fijian Dollar', code: 'FJD'),
  const ItemCurrency(name: 'Falkland Islands Pound', code: 'FKP'),
  const ItemCurrency(name: 'Faroese Króna', code: 'FOK'),
  const ItemCurrency(name: 'British Pound', code: 'GBP'),
  const ItemCurrency(name: 'Georgian Lari', code: 'GEL'),
  const ItemCurrency(name: 'Guernsey Pound', code: 'GGP'),
  const ItemCurrency(name: 'Ghanaian Cedi', code: 'GHS'),
  const ItemCurrency(name: 'Gibraltar Pound', code: 'GIP'),
  const ItemCurrency(name: 'Gambian Dalasi', code: 'GMD'),
  const ItemCurrency(name: 'Guinean Franc', code: 'GNF', digits: 0),
  const ItemCurrency(name: 'Guatemalan Quetzal', code: 'GTQ'),
  const ItemCurrency(name: 'Guyanese Dollar', code: 'GYD'),
  const ItemCurrency(name: 'Hong Kong Dollar', code: 'HKD'),
  const ItemCurrency(name: 'Honduran Lempira', code: 'HNL'),
  const ItemCurrency(name: 'Croatian Kuna', code: 'HRK'),
  const ItemCurrency(name: 'Haitian Gourde', code: 'HTG'),
  const ItemCurrency(name: 'Hungarian Forint', code: 'HUF'),
  const ItemCurrency(name: 'Indonesian Rupiah', code: 'IDR'),
  const ItemCurrency(name: 'Israeli New Shekel', code: 'ILS'),
  const ItemCurrency(name: 'Isle of Man Pound', code: 'IMP'),
  const ItemCurrency(name: 'Indian Rupee', code: 'INR'),
  const ItemCurrency(name: 'Iraqi Dinar', code: 'IQD', digits: 3),
  const ItemCurrency(name: 'Iranian Rial', code: 'IRR'),
  const ItemCurrency(name: 'Icelandic Króna', code: 'ISK', digits: 0),
  const ItemCurrency(name: 'Jersey Pound', code: 'JEP'),
  const ItemCurrency(name: 'Jamaican Dollar', code: 'JMD'),
  const ItemCurrency(name: 'Jordanian Dinar', code: 'JOD', digits: 3),
  const ItemCurrency(name: 'Japanese Yen', code: 'JPY', digits: 0),
  const ItemCurrency(name: 'Kenyan Shilling', code: 'KES'),
  const ItemCurrency(name: 'Kyrgyzstani Som', code: 'KGS'),
  const ItemCurrency(name: 'Cambodian Riel', code: 'KHR'),
  const ItemCurrency(name: 'Kiribati Dollar', code: 'KID'),
  const ItemCurrency(name: 'Comorian Franc', code: 'KMF', digits: 0),
  const ItemCurrency(name: 'South Korean Won', code: 'KRW', digits: 0),
  const ItemCurrency(name: 'Kuwaiti Dinar', code: 'KWD', digits: 3),
  const ItemCurrency(name: 'Cayman Islands Dollar', code: 'KYD'),
  const ItemCurrency(name: 'Kazakhstani Tenge', code: 'KZT'),
  const ItemCurrency(name: 'Lao Kip', code: 'LAK'),
  const ItemCurrency(name: 'Lebanese Pound', code: 'LBP'),
  const ItemCurrency(name: 'Sri Lankan Rupee', code: 'LKR'),
  const ItemCurrency(name: 'Liberian Dollar', code: 'LRD'),
  const ItemCurrency(name: 'Lesotho Loti', code: 'LSL'),
  const ItemCurrency(name: 'Libyan Dinar', code: 'LYD', digits: 3),
  const ItemCurrency(name: 'Moroccan Dirham', code: 'MAD'),
  const ItemCurrency(name: 'Moldovan Leu', code: 'MDL'),
  const ItemCurrency(name: 'Malagasy Ariary', code: 'MGA'),
  const ItemCurrency(name: 'Macedonian Denar', code: 'MKD'),
  const ItemCurrency(name: 'Myanmar Kyat', code: 'MMK'),
  const ItemCurrency(name: 'Mongolian Tögrög', code: 'MNT'),
  const ItemCurrency(name: 'Macanese Pataca', code: 'MOP'),
  const ItemCurrency(name: 'Mauritanian Ouguiya', code: 'MRU'),
  const ItemCurrency(name: 'Mauritian Rupee', code: 'MUR'),
  const ItemCurrency(name: 'Maldivian Rufiyaa', code: 'MVR'),
  const ItemCurrency(name: 'Malawian Kwacha', code: 'MWK'),
  const ItemCurrency(name: 'Mexican Peso', code: 'MXN'),
  const ItemCurrency(name: 'Malaysian Ringgit', code: 'MYR'),
  const ItemCurrency(name: 'Mozambican Metical', code: 'MZN'),
  const ItemCurrency(name: 'Namibian Dollar', code: 'NAD'),
  const ItemCurrency(name: 'Nigerian Naira', code: 'NGN'),
  const ItemCurrency(name: 'Nicaraguan Córdoba', code: 'NIO'),
  const ItemCurrency(name: 'Norwegian Krone', code: 'NOK'),
  const ItemCurrency(name: 'Nepalese Rupee', code: 'NPR'),
  const ItemCurrency(name: 'New Zealand Dollar', code: 'NZD'),
  const ItemCurrency(name: 'Omani Rial', code: 'OMR', digits: 3),
  const ItemCurrency(name: 'Panamanian Balboa', code: 'PAB'),
  const ItemCurrency(name: 'Peruvian Sol', code: 'PEN'),
  const ItemCurrency(name: 'Papua New Guinean Kina', code: 'PGK'),
  const ItemCurrency(name: 'Philippine Peso', code: 'PHP'),
  const ItemCurrency(name: 'Pakistani Rupee', code: 'PKR'),
  const ItemCurrency(name: 'Polish Złoty', code: 'PLN'),
  const ItemCurrency(name: 'Paraguayan Guaraní', code: 'PYG', digits: 0),
  const ItemCurrency(name: 'Qatari Riyal', code: 'QAR'),
  const ItemCurrency(name: 'Romanian Leu', code: 'RON'),
  const ItemCurrency(name: 'Serbian Dinar', code: 'RSD'),
  const ItemCurrency(name: 'Russian Ruble', code: 'RUB'),
  const ItemCurrency(name: 'Rwandan Franc', code: 'RWF', digits: 0),
  const ItemCurrency(name: 'Saudi Riyal', code: 'SAR'),
  const ItemCurrency(name: 'Solomon Islands Dollar', code: 'SBD'),
  const ItemCurrency(name: 'Seychellois Rupee', code: 'SCR'),
  const ItemCurrency(name: 'Sudanese Pound', code: 'SDG'),
  const ItemCurrency(name: 'Swedish Krona', code: 'SEK'),
  const ItemCurrency(name: 'Singapore Dollar', code: 'SGD'),
  const ItemCurrency(name: 'Saint Helena Pound', code: 'SHP'),
  const ItemCurrency(name: 'Sierra Leonean Leone', code: 'SLL'),
  const ItemCurrency(name: 'Somali Shilling', code: 'SOS'),
  const ItemCurrency(name: 'Surinamese Dollar', code: 'SRD'),
  const ItemCurrency(name: 'South Sudanese Pound', code: 'SSP'),
  const ItemCurrency(name: 'São Tomé and Príncipe Dobra', code: 'STN'),
  const ItemCurrency(name: 'Syrian Pound', code: 'SYP'),
  const ItemCurrency(name: 'Swazi Lilangeni', code: 'SZL'),
  const ItemCurrency(name: 'Thai Baht', code: 'THB'),
  const ItemCurrency(name: 'Tajikistani Somoni', code: 'TJS'),
  const ItemCurrency(name: 'Turkmenistani Manat', code: 'TMT'),
  const ItemCurrency(name: 'Tunisian Dinar', code: 'TND', digits: 3),
  const ItemCurrency(name: 'Tongan Paʻanga', code: 'TOP'),
  const ItemCurrency(name: 'Turkish Lira', code: 'TRY'),
  const ItemCurrency(name: 'Trinidad and Tobago Dollar', code: 'TTD'),
  const ItemCurrency(name: 'Tuvaluan Dollar', code: 'TVD'),
  const ItemCurrency(name: 'New Taiwan Dollar', code: 'TWD'),
  const ItemCurrency(name: 'Tanzanian Shilling', code: 'TZS'),
  const ItemCurrency(name: 'Ukrainian Hryvnia', code: 'UAH'),
  const ItemCurrency(name: 'Ugandan Shilling', code: 'UGX', digits: 0),
  const ItemCurrency(name: 'Uruguayan Peso', code: 'UYU'),
  const ItemCurrency(name: 'Uzbekistani Soʻm', code: 'UZS'),
  const ItemCurrency(name: 'Venezuelan Bolívar', code: 'VES'),
  const ItemCurrency(name: 'Vietnamese Đồng', code: 'VND', digits: 0),
  const ItemCurrency(name: 'Vanuatu Vatu', code: 'VUV', digits: 0),
  const ItemCurrency(name: 'Samoan Tālā', code: 'WST'),
  const ItemCurrency(name: 'Central African CFA Franc', code: 'XAF', digits: 0),
  const ItemCurrency(name: 'East Caribbean Dollar', code: 'XCD'),
  const ItemCurrency(name: 'Special Drawing Rights', code: 'XDR', digits: 0),
  ItemCurrency.defaultCurrency,
  const ItemCurrency(name: 'CFP Franc', code: 'XPF', digits: 0),
  const ItemCurrency(name: 'Yemeni Rial', code: 'YER'),
  const ItemCurrency(name: 'South African Rand', code: 'ZAR'),
  const ItemCurrency(name: 'Zambian Kwacha', code: 'ZMW'),
  const ItemCurrency(name: 'Zimbabwean Dollar', code: 'ZWL'),
];
