name: sanu
description: Sanu point of sale
version: 0.0.1+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  collection: ^1.19.0
  csv: ^6.0.0
  decimal: ^3.0.2
  drift: ^2.24.0
  drift_flutter: ^0.2.4
  equatable: ^2.0.7
  file_saver: ^0.2.14
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.7.2
  google_fonts: ^6.2.1
  hydrated_bloc: ^9.1.5
  intl: ^0.19.0
  json_annotation: ^4.9.0
  material_symbols_icons: ^4.2801.1
  meta: ^1.15.0
  package_info_plus: ^8.1.4
  path_provider: ^2.1.5
  provider: ^6.1.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  arbify:
    path: ../../cofinger/arbify_flutter
  bloc_test: ^9.1.7
  build_runner: ^2.4.14
  drift_dev: ^2.24.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

arbify:
  url: http://localhost:8444
  project_id: 5
  output_dir: lib/l10n/arb

flutter:
  uses-material-design: true
  generate: true
