part of 'item_cubit.dart';

extension ItemCubitMock on ItemCubit {
  Future<void> mock() async {
    final additionalItems = [
      {'name': 'Orange', 'categoryId': 0},
      {'name': 'Grapes', 'categoryId': 0},
      {'name': 'Spinach', 'categoryId': 2},
      {'name': 'Potato', 'categoryId': 2},
      {'name': 'Hot Sauce', 'categoryId': 19},
      {'name': 'Barbecue Sauce', 'categoryId': 19},
      {'name': 'Lollipop', 'categoryId': 25},
      {'name': 'Candy Cane', 'categoryId': 25},
      {'name': 'Baby Wipes', 'categoryId': 28},
      {'name': 'Baby Lotion', 'categoryId': 28},
      {'name': 'Paper Towels', 'categoryId': 40},
      {'name': 'Toilet Paper', 'categoryId': 40},
      {'name': 'Bandages', 'categoryId': 44},
      {'name': 'Cough Syrup', 'categoryId': 44},
      {'name': 'Conditioner', 'categoryId': 45},
      {'name': 'Foundation', 'categoryId': 45},
      {'name': 'Car Battery', 'categoryId': 60},
      {'name': 'Windshield Wipers', 'categoryId': 60},
      {'name': 'Jacket', 'categoryId': 61},
      {'name': 'Dress', 'categoryId': 61},
      {'name': 'Boots', 'categoryId': 62},
      {'name': 'Flip Flops', 'categoryId': 62},
      {'name': 'Easter Eggs', 'categoryId': 86},
      {'name': 'Thanksgiving Decorations', 'categoryId': 86},
      {'name': 'Stapler', 'categoryId': 91},
      {'name': 'Highlighters', 'categoryId': 91},
      {'name': 'Drawer Organizers', 'categoryId': 101},
      {'name': 'Shelf Dividers', 'categoryId': 101},
      {'name': 'Pineapple', 'categoryId': 0},
      {'name': 'Strawberries', 'categoryId': 0},
      {'name': 'Lettuce', 'categoryId': 2},
      {'name': 'Cucumber', 'categoryId': 2},
      {'name': 'Ketchup', 'categoryId': 19},
      {'name': 'Mustard', 'categoryId': 19},
      {'name': 'Gum', 'categoryId': 25},
      {'name': 'Chocolate', 'categoryId': 25},
      {'name': 'Baby Shampoo', 'categoryId': 28},
      {'name': 'Baby Oil', 'categoryId': 28},
      {'name': 'Cleaning Spray', 'categoryId': 40},
      {'name': 'Sponges', 'categoryId': 40},
      {'name': 'First Aid Kit', 'categoryId': 44},
      {'name': 'Antibiotic Ointment', 'categoryId': 44},
      {'name': 'Hair Gel', 'categoryId': 45},
      {'name': 'Mascara', 'categoryId': 45},
      {'name': 'Tire Cleaner', 'categoryId': 60},
      {'name': 'Air Freshener', 'categoryId': 60},
      {'name': 'Sweater', 'categoryId': 61},
      {'name': 'Skirt', 'categoryId': 61},
      {'name': 'Dress Shoes', 'categoryId': 62},
      {'name': 'Slippers', 'categoryId': 62},
      {'name': 'Valentine Cards', 'categoryId': 86},
      {'name': 'Fourth of July Flags', 'categoryId': 86},
      {'name': 'Printer Paper', 'categoryId': 91},
      {'name': 'Paper Clips', 'categoryId': 91},
      {'name': 'Hangers', 'categoryId': 101},
      {'name': 'Storage Boxes', 'categoryId': 101},
      {'name': 'Blueberries', 'categoryId': 0},
      {'name': 'Watermelon', 'categoryId': 0},
      {'name': 'Peppers', 'categoryId': 2},
      {'name': 'Onions', 'categoryId': 2},
      {'name': 'Pasta Sauce', 'categoryId': 19},
      {'name': 'Salad Dressing', 'categoryId': 19},
      {'name': 'Marshmallows', 'categoryId': 25},
      {'name': 'Hard Candy', 'categoryId': 25},
      {'name': 'Baby Powder', 'categoryId': 28},
      {'name': 'Baby Soap', 'categoryId': 28},
      {'name': 'Glass Cleaner', 'categoryId': 40},
      {'name': 'Mop', 'categoryId': 40},
      {'name': 'Thermometer', 'categoryId': 44},
      {'name': 'Allergy Medicine', 'categoryId': 44},
      {'name': 'Hair Spray', 'categoryId': 45},
      {'name': 'Blush', 'categoryId': 45},
      {'name': 'Car Mats', 'categoryId': 60},
      {'name': 'GPS', 'categoryId': 60},
      {'name': 'Blouse', 'categoryId': 61},
      {'name': 'Shorts', 'categoryId': 61},
      {'name': 'Running Shoes', 'categoryId': 62},
      {'name': 'Heels', 'categoryId': 62},
      {'name': 'Christmas Lights', 'categoryId': 86},
      {'name': 'New Year Party Supplies', 'categoryId': 86},
      {'name': 'Envelopes', 'categoryId': 91},
      {'name': 'Markers', 'categoryId': 91},
      {'name': 'Closet Rods', 'categoryId': 101},
      {'name': 'Under Bed Storage', 'categoryId': 101},
      {'name': 'Mango', 'categoryId': 0},
      {'name': 'Peach', 'categoryId': 0},
      {'name': 'Zucchini', 'categoryId': 2},
      {'name': 'Garlic', 'categoryId': 2},
      {'name': 'Pizza Sauce', 'categoryId': 19},
      {'name': 'Tartar Sauce', 'categoryId': 19},
      {'name': 'Chewing Gum', 'categoryId': 25},
      {'name': 'Jelly Beans', 'categoryId': 25},
      {'name': 'Baby Toothpaste', 'categoryId': 28},
      {'name': 'Baby Toothbrush', 'categoryId': 28},
      {'name': 'Fabric Softener', 'categoryId': 40},
      {'name': 'Bleach', 'categoryId': 40},
      {'name': 'Hand Sanitizer', 'categoryId': 44},
      {'name': 'Antacid', 'categoryId': 44},
      {'name': 'Body Wash', 'categoryId': 45},
      {'name': 'Nail Polish', 'categoryId': 45},
      {'name': 'Car Cover', 'categoryId': 60},
      {'name': 'Jump Starter', 'categoryId': 60},
      {'name': 'Pants', 'categoryId': 61},
      {'name': 'Socks', 'categoryId': 61},
      {'name': 'Loafers', 'categoryId': 62},
      {'name': 'Clogs', 'categoryId': 62},
      {'name': 'Birthday Decorations', 'categoryId': 86},
      {'name': 'Wedding Decorations', 'categoryId': 86},
      {'name': 'Scissors', 'categoryId': 91},
      {'name': 'Tape', 'categoryId': 91},
      {'name': 'Shoe Rack', 'categoryId': 101},
      {'name': 'Laundry Basket', 'categoryId': 101},
    ];

    for (final itemElement in additionalItems) {
      final name = itemElement['name']! as String;
      final category = itemElement['categoryId']! as int;
      final item = ItemTableData(
        id: (additionalItems.indexOf(itemElement) + 1).toString(),
        name: name,
        description: 'Description for $name',
        image: 'https://placehold.co/400',
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        price: (Random().nextInt(1000000 - 50) + 50).toString(),
        category: category.toString(),
      );
      await database.into(database.itemTable).insertOnConflictUpdate(item);
    }
    await load();
  }

  Future<void> dropItemTable() async {
    await database.delete(database.itemTable).go();
    await load();
  }
}
